### PR TITLE
Allow custom host header

### PR DESCRIPTION
**Pull request by nerdyness**
A custom host header might not be useful for the majority of people but I do currently have a use-case for it.

### CODE REVIEW

**Comment by Hobbsee** [comment]
Looks reasonable.  What do you think about setting a custom user agent as well?

**Comment by nerdyness** [comment]
>  What do you think about setting a custom user agent as well?

Never a bad idea! I'll set that up with a sensible default :+1:

I've just added some doco for this new feature as well.

**Comment by nerdyness** [comment]
Take another look, @Hobbsee. This attempt is much more thought out :smile:

**Comment by Hobbsee** [comment]
Looks good to me - thanks!

**Comment by nerdyness** [comment]
I've built the gem and push'd it to rubygems #ftw

**Pull request merged**
